language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
    - "pip install -r ./requirements.txt"
    - "pip install -r ./dev_requirements.txt"
# command to run tests
script: 
    - "pytest --cov=./"
    - "pycodestyle . --show-source --show-pep8"
    - "codecov"
    - "python ./freezer.py bdist_rpm"
